### ISSUE TITLE
 Inquiry Regarding Dataset Selection in DGInStyle_Datasets\half_adverse_half_normal

### ISSUE THREAD

**Issue by JimmyPang02** [prs-eth/DGInStyle#1]
Hello! I want to start by thanking you for your incredible work. I'm in the process of replicating your paper for my undergraduate thesis and have questions regarding the DGInStyle_Datasets\half_adverse_half_normal dataset.

Could you explain the selection process for the 7000 generated images included in this dataset? Specifically, I noticed there are 3000 images labeled with 'a', 1000 with 'n', and 3000 without any letter. What do these labels represent?

Thank you for your guidance and assistance.

**Comment by yurujaja** [comment]
Thank you for your interest in our work. In the generated dataset, images tagged 'a' indicate usage of text prompts with adverse weather, excluding night situations. 'n' signifies prompts for night scenarios. Images without a letter don't involve any adverse conditions.

**Comment by JimmyPang02** [comment]
> Thank you for your interest in our work. In the generated dataset, images tagged 'a' indicate usage of text prompts with adverse weather, excluding night situations. 'n' signifies prompts for night scenarios. Images without a letter don't involve any adverse conditions.

Thank you very much for your prompt reply and the detailed explanation; it was immensely helpful! If I may, I have an additional question regarding the training process of the DGInstyle model. Did the final model training exclusively utilize the DGInStyle_Datasets\half_adverse_half_normal dataset, or was it trained on a combination of the GTA dataset and the DGInStyle_Datasets\half_adverse_half_normal dataset? I appreciate your guidance on this.

**Comment by yurujaja** [comment]
It was trained on a combination of the GTA dataset and the DGInStyle_Datasets. This is also mentioned in the implementation details section of the papaer.
